apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  namespace: user07-coffee
  labels:
    app: report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
    spec:
      #volumes:
      #  - name: persistent-storage
      #    persistentVolumeClaim:
      #      claimName: efs-claim
      containers:
        - name: report
          image: 879772956301.dkr.ecr.ap-northeast-1.amazonaws.com/user07-report:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: report-config
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          #volumeMounts:
          #  - name: persistent-storage
          #    mountPath: /data