apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  namespace: coffee
  labels:
    app: report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
        - name: report
          image: 740569282574.dkr.ecr.ap-northeast-2.amazonaws.com/report:v5
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: report-config
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5