apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: user07-coffee
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: 879772956301.dkr.ecr.ap-northeast-1.amazonaws.com/user07-product:v1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 400m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 1000Mi
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5