apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: benefit
  namespace: user07-coffee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: benefit
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
