apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order
  namespace: coffee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
