apiVersion: apps/v1
kind: Deployment
metadata:
  name: benefit
  namespace: user07-coffee
  labels:
    app: benefit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benefit
  template:
    metadata:
      labels:
        app: benefit
    spec:
      containers:
        - name: benefit
          image: 879772956301.dkr.ecr.ap-northeast-1.amazonaws.com/user07-benefit:v3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: benefit-config
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5